version: '3.1'
services:
  db:
    image: postgres
    container_name: skillupcs-postgres
    restart: always 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: skillupcs
    ports:
      - "5432:5432" 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data